### ISSUE TITLE
Follow semantic versioning in BSP (BSP-135)

### ISSUE THREAD

**Issue by tore-espressif** [espressif/esp-bsp#10]
Most dependencies are defined as `>=`, this may work, but in general is not compatible with semantic versioning that we are using.

I would suggest "^1.1.1" (>=1.1.1,<2.0.0) or "~1.1.1" (>=1.1.1,<1.2.0) requirements,

like

```
dependencies:
  idf: ">=4.2"

  button:
    version: "^1.0.0"
    public: true
  es8311:
    version: "^0.0.2-alpha"
    public: true
  led_strip:
    version: "^1.1.0-alpha"
    public: true
  lvgl/lvgl_esp32_drivers:
    version: "^0.0.3"
    public: true
```

- [x] Kaluga
- [x] Azure
- [x] Wrover
