### ISSUE TITLE
GT911 init error: Custom wiring on WaveShare 7 inch (BSP-273)

### ISSUE THREAD

**Issue by hayschan** [espressif/esp-bsp#130]
## Pin mapping

I designed a custom PCB that connect the WaveShare 7 inch in the following pin mapping.

```c
/* I2C */
#define BSP_I2C_SCL           (GPIO_NUM_47)
#define BSP_I2C_SDA           (GPIO_NUM_21)

/* Display */
#define BSP_LCD_WIDTH   (16)
#define BSP_LCD_DB0     (GPIO_NUM_12)
#define BSP_LCD_DB1     (GPIO_NUM_13)
#define BSP_LCD_DB2     (GPIO_NUM_10)
#define BSP_LCD_DB3     (GPIO_NUM_11)
#define BSP_LCD_DB4     (GPIO_NUM_46)
#define BSP_LCD_DB5     (GPIO_NUM_9)
#define BSP_LCD_DB6     (GPIO_NUM_8)
#define BSP_LCD_DB7     (GPIO_NUM_3)
#define BSP_LCD_DB8     (GPIO_NUM_17)
#define BSP_LCD_DB9     (GPIO_NUM_18)
#define BSP_LCD_DB10    (GPIO_NUM_41)
#define BSP_LCD_DB11    (GPIO_NUM_42)
#define BSP_LCD_DB12    (GPIO_NUM_39)
#define BSP_LCD_DB13    (GPIO_NUM_40)
#define BSP_LCD_DB14    (GPIO_NUM_37)
#define BSP_LCD_DB15    (GPIO_NUM_38)
#define BSP_LCD_CS      (GPIO_NUM_NC)
#define BSP_LCD_DC      (GPIO_NUM_4)
#define BSP_LCD_WR      (GPIO_NUM_36) 
#define BSP_LCD_RD      (GPIO_NUM_NC)
#define BSP_LCD_RST     (GPIO_NUM_35)
#define BSP_LCD_WAIT    (GPIO_NUM_48)
#define BSP_LCD_BL      (GPIO_NUM_NC)
#define BSP_LCD_TP_INT  (GPIO_NUM_45)
```

## Error code

However, when I connect the PCB to the display. It gives out GT911 related error. It fails to initialize.

```python
I (685) gpio: GPIO[35]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (685) gpio: GPIO[48]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (715) gpio: GPIO[45]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
E (715) lcd_panel.io.i2c: panel_io_i2c_rx_buffer(119): i2c transaction failed
E (725) GT911: touch_gt911_read_cfg(239): GT911 read error!
E (725) GT911: esp_lcd_touch_new_i2c_gt911(99): GT911 init failed
E (735) GT911: Error (0xffffffff)! Touch controller GT911 initialization failed!
I (745) gpio: GPIO[45]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0

assert failed: bsp_display_lock ws_7inch.c:386 (lvgl_mux && "bsp_display_start must be called first")
```

### Pin are connected respectively

I made sure the pin on the WaveShare GT911 LCD are connected to the respective GPIO. I used a multimeter that beeps if it connects. Every pin is correct.

Is there any other thing I might miss?

**Comment by hayschan** [comment]
When I connect the WaveShare 7 inch LCD GT911 using the default wiring and use [default wiring header](https://github.com/espressif/esp-bsp/blob/master/SquareLine/boards/custom_waveshare_7inch/components/ws_7inch/include/bsp/ws_7inch.h), everything is good.

**Comment by hayschan** [comment]
The version I am using is `v1.0.0`:

```yml
version: "1.0.0"
description: Board Support Package for WaveShare 7inch
url: https://github.com/espressif/esp-bsp/SquareLine/boards/custom_waveshare_7inch/components/ws_7inch

dependencies:
  idf: ">=5.0"
  esp_lcd_ra8875: "^1"
  esp_lcd_touch_gt911: "^1"

  lvgl/lvgl:
    version: "^8"
    public: true
```
