### ISSUE TITLE
esp_lvgl_port appears to lack declaration of lv_tick_inc() (BSP-335)

### ISSUE THREAD

**Issue by dannybackx** [espressif/esp-bsp#191]
In an esp32 project with these dependencies
```
dependencies:
  lvgl/lvgl: "*"
  espressif/esp_lcd_touch: "*"
  espressif/esp_lvgl_port: "*"
  espressif/esp_lcd_touch_gt911: "==1.0.0"

```
there is always a compile error because in managed_components/espressif__esp_lvgl_port/esp_lvgl_port.c around line 790, lv_tick_inc() isn't declared. So I added a single line in my copy as such : 
```
static void lvgl_port_tick_increment(void *arg)
{
    void lv_tick_inc(uint32_t);

    /* Tell LVGL how many milliseconds have elapsed */
    lv_tick_inc(lvgl_port_timer_period_ms);
}

```
I can't find a setting to automate this so I'm guessing it's an oversight.
Example : https://sourceforge.net/p/esp32s3-4827s043/code/HEAD/tree/trunk/lvgl-port .

Thanks,
  Danny
